# This patch add annotation to admission webhook config and
# the variables $(IPAM_CERTIFICATE_NAMESPACE) and $(IPAM_CERTIFICATE_NAME) will be substituted by kustomize.
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: $(IPAM_CERTIFICATE_NAMESPACE)/$(IPAM_CERTIFICATE_NAME)
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: $(IPAM_CERTIFICATE_NAMESPACE)/$(IPAM_CERTIFICATE_NAME)
